<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-3EO8411" ignored="3" name="Test" tests="6" failures="1" timestamp="2022-05-25T22:21:09 GMT+07:00" time="0.047" errors="0">
  <testcase name="test1" time="0.007" classname="online_tusur.unit_online_tusur.NewTest"/>
  <testcase name="test5" time="0.001" classname="online_tusur.unit_online_tusur.NewTest"/>
  <testcase name="test5" time="0.001" classname="online_tusur.unit_online_tusur.NewTest"/>
  <testcase name="test5" time="0.001" classname="online_tusur.unit_online_tusur.NewTest"/>
  <testcase name="test5" time="0.0" classname="online_tusur.unit_online_tusur.NewTest"/>
  <testcase name="test5" time="0.001" classname="online_tusur.unit_online_tusur.NewTest">
    <failure type="java.lang.AssertionError" message="expected [18] but found [50]">
      <![CDATA[java.lang.AssertionError: expected [18] but found [50]
at online_tusur.unit_online_tusur.NewTest.test5(NewTest.java:36)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- test5 -->
  <testcase name="test3" time="0.0" classname="online_tusur.unit_online_tusur.NewTest">
    <ignored/>
  </testcase> <!-- test3 -->
  <testcase name="test4" time="0.0" classname="online_tusur.unit_online_tusur.NewTest">
    <ignored/>
  </testcase> <!-- test4 -->
  <testcase name="test2" time="0.0" classname="online_tusur.unit_online_tusur.NewTest">
    <ignored/>
  </testcase> <!-- test2 -->
</testsuite> <!-- Test -->
